import type { TrendPoint } from "../domain/runAnalytics";

export function MiniTrend({ title, unit, points, empty, selectedTimeNs, onSelect }: { title: string; unit: string; points: readonly TrendPoint[]; empty: string; selectedTimeNs?: string | null; onSelect?: (timeNs: string) => void }) {
  if (!points.length) return <article className="trend-card"><div><strong>{title}</strong><span>{unit}</span></div><p>{empty}</p></article>;
  const times = points.map((point) => BigInt(point.timeNs)); const minT = times.reduce((a, b) => a < b ? a : b); const maxT = times.reduce((a, b) => a > b ? a : b); const values = points.map((point) => point.value); const minV = Math.min(...values); const maxV = Math.max(...values);
  const positions = points.map((point, index) => ({ point, x: 18 + Number((times[index] - minT) * 1000n / (maxT - minT || 1n)) / 1000 * 264, y: 72 - ((point.value - minV) / Math.max(maxV - minV, 1e-18)) * 52 }));
  const coords = positions.map(({ x, y }) => `${x},${y}`).join(" ");
  return <article className="trend-card"><div><strong>{title}</strong><span>{points.at(-1)?.value} {unit}</span></div><svg viewBox="0 0 300 105" role="img" aria-label={`${title}趋势`}><path d="M18 72H282" className="trend-axis" /><polyline points={coords} className="trend-line" />{positions.map(({ point, x, y }) => <circle key={`${point.timeNs}:${point.value}`} cx={x} cy={y} r={point.timeNs === selectedTimeNs ? 5 : 3} className={point.timeNs === selectedTimeNs ? "trend-point selected" : "trend-point"} onClick={() => onSelect?.(point.timeNs)}><title>{`${point.value} ${unit} @ ${point.timeNs} ns`}</title></circle>)}<text x="18" y="94" className="trend-time-label">{Number(minT) / 1e9} s</text><text x="282" y="94" textAnchor="end" className="trend-time-label">{Number(maxT) / 1e9} s</text></svg><small>{points.length} 个正式观测点 · 横轴为仿真时间</small></article>;
}
