import { useMemo, useState } from "react";
import type { ScenarioDraft } from "../domain/workspace";

interface Props { draft: ScenarioDraft; onChange: (draft: ScenarioDraft) => void; maximumDepthMeters?: number; maximumRangeMeters?: number; initialSelectedIds?: readonly string[] }

export function ScenarioDesigner({ draft, onChange, maximumDepthMeters, maximumRangeMeters, initialSelectedIds }: Props) {
  const [selectedIds, setSelectedIds] = useState<string[]>(() => {
    const requested = (initialSelectedIds ?? []).filter((id) => draft.nodes.some((node) => node.node_id === id)).slice(0, 2);
    return requested.length ? requested : draft.nodes[0] ? [draft.nodes[0].node_id] : [];
  });
  const selected = draft.nodes.find((node) => node.node_id === selectedIds[0]);
  const peer = draft.nodes.find((node) => node.node_id === selectedIds[1]);
  const bounds = useMemo(() => Math.max(1000, maximumRangeMeters ? maximumRangeMeters / 2 : 0, ...draft.nodes.flatMap((node) => [Math.abs(node.initial_position.x_meters), Math.abs(node.initial_position.y_meters)])) * 1.12, [draft.nodes, maximumRangeMeters]);
  const viewX = (value: number) => 350 + (value / bounds) * 290;
  const viewY = (value: number) => 260 - (value / bounds) * 210;
  const distance = selected && peer ? Math.hypot(selected.initial_position.x_meters - peer.initial_position.x_meters, selected.initial_position.y_meters - peer.initial_position.y_meters, selected.initial_position.z_meters - peer.initial_position.z_meters) : null;
  const selectNode = (nodeId: string, pair = false) => pair ? setSelectedIds((current) => current[0] === nodeId ? [nodeId] : [current[0] ?? nodeId, nodeId]) : setSelectedIds([nodeId]);
  const updateNode = (patch: Partial<NonNullable<typeof selected>>) => onChange({ ...draft, nodes: draft.nodes.map((node) => node.node_id === selected?.node_id ? { ...node, ...patch } : node) });
  const addNode = () => {
    let id = 0n; const ids = new Set(draft.nodes.map((node) => node.node_id)); while (ids.has(id.toString())) id += 1n;
    const node = { node_id: id.toString(), can_transmit: true, can_receive: true, duplex_mode: "HalfDuplex", initial_position: { x_meters: 0, y_meters: 0, z_meters: -20 }, initial_velocity: { x_meters_per_second: 0, y_meters_per_second: 0, z_meters_per_second: 0 } };
    onChange({ ...draft, nodes: [...draft.nodes, node] }); setSelectedIds([node.node_id]);
  };
  const drag = (event: React.PointerEvent<SVGSVGElement>) => {
    if (!selected || event.buttons !== 1) return; const rect = event.currentTarget.getBoundingClientRect(); const x = ((event.clientX - rect.left) / rect.width) * 700; const y = ((event.clientY - rect.top) / rect.height) * 520;
    updateNode({ initial_position: { ...selected.initial_position, x_meters: Math.round(((x - 350) / 290) * bounds), y_meters: Math.round(((260 - y) / 210) * bounds) } });
  };
  const depthScale = Math.max(maximumDepthMeters ?? 0, ...draft.nodes.map((node) => Math.abs(node.initial_position.z_meters)), 1);
  return <div className="scenario-studio">
    <aside className="studio-tools" aria-label="场景节点工具"><div className="studio-pane-title"><span>节点</span><button type="button" onClick={addNode} aria-label="＋ 添加节点">＋</button></div><div className="node-tool-list">{draft.nodes.map((node) => <button type="button" key={node.node_id} className={selectedIds.includes(node.node_id) ? "selected" : ""} onClick={(event) => selectNode(node.node_id, event.shiftKey)}><i className={node.node_id === draft.fusionCenterNodeId ? "fusion" : "participant"} /><span><strong>N{node.node_id}</strong><small>{node.node_id === draft.fusionCenterNodeId ? "融合中心" : node.can_transmit && node.can_receive ? "收发节点" : node.can_receive ? "接收节点" : "发送节点"}</small></span></button>)}</div><div className="tool-help"><b>选择与测距</b><span>单击选择；Shift + 单击第二节点查看三维距离。</span></div></aside>
    <section className="studio-canvas"><div className="canvas-toolbar"><strong>平面布设</strong><span>水域范围 ±{Math.round(bounds)} m · {draft.nodes.length} 个节点</span>{distance !== null && <b className="distance-readout">N{selected?.node_id} ↔ N{peer?.node_id} · {distance.toFixed(1)} m</b>}<div className="canvas-legend"><i className="fusion" /> 融合中心 <i className="participant" /> 通信节点</div></div>
      <svg viewBox="0 0 700 520" role="img" aria-label="可编辑场景画布" onPointerMove={drag}><defs><pattern id="studio-grid" width="58" height="52" patternUnits="userSpaceOnUse"><path d="M58 0H0V52" className="grid-line" /></pattern></defs><rect width="700" height="520" className="water-boundary" /><rect x="20" y="20" width="660" height="480" fill="url(#studio-grid)" className="workspace-boundary" /><line x1="350" y1="20" x2="350" y2="500" className="plot-axis" /><line x1="20" y1="260" x2="680" y2="260" className="plot-axis" /><text x="28" y="42" className="plot-label">环境：{draft.environmentAssetId || "未绑定"}</text><text x="620" y="492" className="plot-label">X / m</text><text x="358" y="38" className="plot-label">Y / m</text>
      {draft.nodes.flatMap((from, index) => draft.nodes.slice(index + 1).map((to) => <line key={`${from.node_id}-${to.node_id}`} x1={viewX(from.initial_position.x_meters)} y1={viewY(from.initial_position.y_meters)} x2={viewX(to.initial_position.x_meters)} y2={viewY(to.initial_position.y_meters)} className={selectedIds.includes(from.node_id) && selectedIds.includes(to.node_id) ? "geometry-link measured" : "geometry-link"} />))}
      {draft.nodes.map((node) => <g key={node.node_id} transform={`translate(${viewX(node.initial_position.x_meters)} ${viewY(node.initial_position.y_meters)})`} onPointerDown={(event) => { event.currentTarget.setPointerCapture(event.pointerId); selectNode(node.node_id, event.shiftKey); }} className="draggable-node"><circle r={node.node_id === draft.fusionCenterNodeId ? 18 : 14} className={selectedIds[0] === node.node_id ? "node-selected" : selectedIds[1] === node.node_id ? "node-peer" : node.node_id === draft.fusionCenterNodeId ? "node-fusion" : "node-participant"} /><circle r="25" className={selectedIds.includes(node.node_id) ? "selection-halo" : "selection-halo hidden"} /><text x="22" y="5" className="node-label">N{node.node_id}</text><text x="22" y="20" className="node-depth">{Math.abs(node.initial_position.z_meters)} m 深</text></g>)}</svg>
      <div className="depth-workspace" aria-label="节点深度剖面"><div className="sea-surface"><span>海面 0 m</span></div><div className="sea-floor" />{draft.nodes.map((node, index) => <button type="button" key={node.node_id} onClick={(event) => selectNode(node.node_id, event.shiftKey)} className={selectedIds.includes(node.node_id) ? "selected" : ""} style={{ left: `${7 + index * (86 / Math.max(draft.nodes.length - 1, 1))}%`, top: `${10 + Math.min(68, Math.abs(node.initial_position.z_meters) / depthScale * 68)}%` }}>N{node.node_id}<small>{Math.abs(node.initial_position.z_meters)} m</small></button>)}</div>
      <div className="studio-statusbar"><span>主选：{selected ? `N${selected.node_id} · (${selected.initial_position.x_meters}, ${selected.initial_position.y_meters}, ${selected.initial_position.z_meters}) m` : "无"}</span><span>{peer ? `N${selected?.node_id} ↔ N${peer.node_id}` : "Shift + 选择第二节点测距"}</span><strong>{distance === null ? "—" : `${distance.toFixed(1)} m`}</strong></div></section>
    <aside className="property-panel"><div className="studio-pane-title"><span>节点属性</span><small>{selected ? `N${selected.node_id}` : "未选择"}</small></div>{!selected ? <p>请在节点列表或画布中选择节点。</p> : <><label>节点编号<input value={selected.node_id} disabled /></label><h3>空间位置</h3><div className="form-grid"><label>X（m）<input type="number" value={selected.initial_position.x_meters} onChange={(event) => updateNode({ initial_position: { ...selected.initial_position, x_meters: Number(event.target.value) } })} /></label><label>Y（m）<input type="number" value={selected.initial_position.y_meters} onChange={(event) => updateNode({ initial_position: { ...selected.initial_position, y_meters: Number(event.target.value) } })} /></label><label>深度（m）<input type="number" min="0" value={Math.abs(selected.initial_position.z_meters)} onChange={(event) => updateNode({ initial_position: { ...selected.initial_position, z_meters: -Math.abs(Number(event.target.value)) } })} /></label></div><h3>通信能力</h3><label className="check"><input type="checkbox" checked={selected.can_transmit} onChange={(event) => updateNode({ can_transmit: event.target.checked })} /> 可发送</label><label className="check"><input type="checkbox" checked={selected.can_receive} onChange={(event) => updateNode({ can_receive: event.target.checked })} /> 可接收</label><label className="check"><input type="radio" checked={draft.fusionCenterNodeId === selected.node_id} onChange={() => onChange({ ...draft, fusionCenterNodeId: selected.node_id })} /> 设为融合中心</label><h3>运动速度（m/s）</h3><div className="form-grid"><label>Vx<input type="number" value={selected.initial_velocity.x_meters_per_second} onChange={(event) => updateNode({ initial_velocity: { ...selected.initial_velocity, x_meters_per_second: Number(event.target.value) } })} /></label><label>Vy<input type="number" value={selected.initial_velocity.y_meters_per_second} onChange={(event) => updateNode({ initial_velocity: { ...selected.initial_velocity, y_meters_per_second: Number(event.target.value) } })} /></label></div><button type="button" className="danger-button" disabled={draft.nodes.length <= 1} onClick={() => { const nodes = draft.nodes.filter((node) => node.node_id !== selected.node_id); onChange({ ...draft, nodes, fusionCenterNodeId: draft.fusionCenterNodeId === selected.node_id ? nodes[0].node_id : draft.fusionCenterNodeId }); setSelectedIds(nodes[0] ? [nodes[0].node_id] : []); }}>删除节点</button></>}</aside>
  </div>;
}
