import type { EnvironmentDto, ExperimentDto, ScenarioDto } from "../api/types";

export type DraftKind = "environment" | "scenario" | "experiment";
export type DraftProvenance =
  | { kind: "new"; label: "新建" }
  | { kind: "derived"; label: string; sourceId: string; sourceVersion?: string; inherited: readonly string[]; omitted: readonly string[] };

export interface EnvironmentDraft { kind: "environment"; id: string; name: string; description: string; provenance: DraftProvenance; maximumDepthMeters: number; maximumRangeMeters: number; centerFrequencyHz: number; soundSpeedProfile: Array<{ depthMeters: number; speedMetersPerSecond: number }>; bathymetry: Array<{ rangeMeters: number; depthMeters: number }>; constructionMode: "BellhopOffline"; updatedAt: string; }
export interface ScenarioDraft { kind: "scenario"; id: string; name: string; environmentAssetId: string; fusionCenterNodeId: string; provenance: DraftProvenance; nodes: ScenarioDto["nodes"]; updatedAt: string; }
export interface ExperimentDraft { kind: "experiment"; id: string; name: string; sourceExperimentId: string | null; scenarioId: string; provenance: DraftProvenance; routingMode: string; macMode: string; bitRateBitsPerSecond: string; centerFrequencyHz: number; occupiedBandwidthHz: number; sourceLevelDb: number; guardIntervalNs: string; simulationCycleCount: string; deterministicSeed: string; networkUpdateIntervalCycles: string; updatedAt: string; }
export type WorkspaceDraft = EnvironmentDraft | ScenarioDraft | ExperimentDraft;
const key = "ns3-bellhop-platform.workbench-drafts.v1";
const now = () => new Date().toISOString();

export function loadDrafts(): WorkspaceDraft[] { try { const value = JSON.parse(localStorage.getItem(key) ?? "[]") as unknown; return Array.isArray(value) ? value.filter(isDraft).map(upgradeDraft) : []; } catch { return []; } }
export function saveDraft(draft: WorkspaceDraft): WorkspaceDraft[] { const next = [...loadDrafts().filter((item) => !(item.kind === draft.kind && item.id === draft.id)), draft]; localStorage.setItem(key, JSON.stringify(next)); window.dispatchEvent(new Event("workbench-drafts-changed")); return next; }
export function deleteDraft(kind: DraftKind, id: string): WorkspaceDraft[] { const next = loadDrafts().filter((item) => !(item.kind === kind && item.id === id)); localStorage.setItem(key, JSON.stringify(next)); window.dispatchEvent(new Event("workbench-drafts-changed")); return next; }

export function newEnvironmentDraft(source?: EnvironmentDto): EnvironmentDraft {
  return { kind: "environment", id: `environment-draft-${Date.now()}`, name: source ? `${source.environment_asset_id} 范围派生草稿` : "未命名声学环境", description: source?.provenance.source_description ?? "", provenance: source ? { kind: "derived", label: `以 ${source.environment_asset_id} 的范围新建`, sourceId: source.environment_asset_id, sourceVersion: source.asset_format_version, inherited: ["范围", "频率", "来源 metadata"], omitted: ["SSP", "Bathymetry", "传播场内容"] } : { kind: "new", label: "新建" }, maximumDepthMeters: source?.axes.receiver_depth.maximum || 100, maximumRangeMeters: source?.axes.horizontal_range.maximum || 5000, centerFrequencyHz: source?.axes.frequency.minimum || 25000, soundSpeedProfile: [], bathymetry: [], constructionMode: "BellhopOffline", updatedAt: now() };
}
export function scenarioDraftFrom(source: ScenarioDto): ScenarioDraft { return { kind: "scenario", id: `scenario-draft-${Date.now()}`, name: `${source.name} 派生草稿`, environmentAssetId: source.environment.environment_asset_id, fusionCenterNodeId: source.fusion_center_node_id, provenance: { kind: "derived", label: `派生自 ${source.scenario_id} v${source.version}`, sourceId: source.scenario_id, sourceVersion: source.version, inherited: ["节点", "环境引用", "融合中心"], omitted: [] }, nodes: structuredClone(source.nodes), updatedAt: now() }; }
export function experimentDraftFrom(source: ExperimentDto): ExperimentDraft { return { kind: "experiment", id: `experiment-draft-${Date.now()}`, name: `${source.name} 派生实验`, sourceExperimentId: source.experiment_id, scenarioId: source.scenario.scenario_id, provenance: { kind: "derived", label: `派生自 ${source.experiment_id} v${source.version}`, sourceId: source.experiment_id, sourceVersion: source.version, inherited: ["场景引用", "网络", "物理层", "执行参数"], omitted: [] }, routingMode: source.routing.mode, macMode: source.mac.mode, bitRateBitsPerSecond: source.phy.bit_rate_bits_per_second, centerFrequencyHz: source.phy.center_frequency_hz, occupiedBandwidthHz: source.phy.occupied_bandwidth_hz, sourceLevelDb: source.phy.source_level_db_re_1upa_at_1m, guardIntervalNs: source.mac.guard_interval_ns, simulationCycleCount: source.simulation_cycle_count, deterministicSeed: source.deterministic_seed, networkUpdateIntervalCycles: source.network_update_interval_cycles, updatedAt: now() }; }
export function validateDraft(draft: WorkspaceDraft): string[] { const issues: string[] = []; if (!draft.name.trim()) issues.push("名称不能为空"); if (draft.kind === "environment") { if (!(draft.maximumDepthMeters > 0)) issues.push("最大水深必须大于 0"); if (!(draft.maximumRangeMeters > 0)) issues.push("最大距离必须大于 0"); if (!(draft.centerFrequencyHz > 0)) issues.push("工作频率必须大于 0"); if (!validPairs(draft.soundSpeedProfile, "depthMeters", "speedMetersPerSecond", draft.maximumDepthMeters)) issues.push("SSP 至少需要两个有效且范围内的采样点"); if (!validPairs(draft.bathymetry, "rangeMeters", "depthMeters", draft.maximumRangeMeters, draft.maximumDepthMeters)) issues.push("Bathymetry 至少需要两个有效且范围内的采样点"); } else if (draft.kind === "scenario") { if (!draft.nodes.length) issues.push("场景至少需要一个节点"); if (!draft.nodes.some((node) => node.node_id === draft.fusionCenterNodeId)) issues.push("融合中心必须是场景内节点"); } else { if (!/^[1-9][0-9]*$/.test(draft.bitRateBitsPerSecond)) issues.push("通信速率必须是正整数"); if (!/^[1-9][0-9]*$/.test(draft.simulationCycleCount)) issues.push("仿真周期数必须是正整数"); if (!/^(0|[1-9][0-9]*)$/.test(draft.deterministicSeed)) issues.push("随机种子必须是非负整数"); } return issues; }
function validPairs<T extends Record<string, number>>(points: readonly T[], first: keyof T, second: keyof T, maximumFirst: number, maximumSecond = Number.POSITIVE_INFINITY): boolean { return points.length >= 2 && points.every((point) => Number.isFinite(point[first]) && Number.isFinite(point[second]) && point[first] >= 0 && point[first] <= maximumFirst && point[second] >= 0 && point[second] <= maximumSecond); }
function isDraft(value: unknown): value is WorkspaceDraft { if (!value || typeof value !== "object") return false; const record = value as Record<string, unknown>; return ["environment", "scenario", "experiment"].includes(String(record.kind)) && typeof record.id === "string" && typeof record.name === "string"; }
function upgradeDraft(draft: WorkspaceDraft): WorkspaceDraft { return "provenance" in draft && draft.provenance ? draft : { ...draft, provenance: { kind: "new", label: "新建" } } as WorkspaceDraft; }
